### ISSUE TITLE
Enable cache for Doctrine annotation in prod env

### ISSUE THREAD

**Issue by damienalexandre** [j0k3r/f43.me#5]
Hi dude,
you should use APC for Doctrine, at least for the metadata (annotation & co) as it's a major performance boost for free :boom: 

``` yaml
doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc
```

![Woah](http://www.reactiongifs.com/wp-content/uploads/2013/01/woah.gif)
